%TOP%
<chat-main>
<chat-body>
<chat-view>
<chat-title>%TITLE%</chat-title>
<chat-chat></chat-chat>
</chat-view>
<chat-nav></chat-nav>
<chat-error></chat-error>
</chat-body>
<chat-panel>
<chat-panel></chat-panel>
</chat-panel>
</chat-main>
<chat-form>
<form></form>
<chat-mysmiles></chat-mysmiles>
</chat-form>
